version: '3.8'

services:
  app:
    image: imgyuri0517/flora_application  # Docker Hub에 푸시할 이미지 이름
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/flora  # MariaDB 연결 URL
      SPRING_DATA_REDIS_HOST: redis  # Redis 연결 호스트
    depends_on:
      - ubuntu-db-1  # db 서비스가 먼저 실행되도록 설정
      - ubuntu-redis-1  # redis 서비스가 먼저 실행되도록 설정
    networks:
      - app-network

networks:
  app-network:
    external: true  # 외부 네트워크를 사용
