version: '3.8'

services:
  app:
    image: imgyuri0517/flora_application
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://localhost:3306/flora  # EC2에서 db 컨테이너와 연결
      SPRING_DATA_REDIS_HOST: localhost  # EC2에서 redis와 연결
    networks:
      - app-network

networks:
  app-network:
    external: true
