version: '3.8'

services:
  app:
    image: imgyuri0517/flora_application
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/flora
      SPRING_DATA_REDIS_HOST: redis
    networks:
      - app-network

networks:
  app-network:
    external: true
